### ISSUE TITLE
Working external ADC VPX in 'tier 1' configuration results in permanent ingress 'Initializing' state

### ISSUE THREAD

**Issue by steviestainz** [citrix/citrix-k8s-ingress-controller#166]
NB It is assumed that CIC 1.x (tested 1.5.x and 1.6.1) supports deployment on Rancher created clusters due to the documentation [here](https://developer-docs.citrix.com/projects/citrix-k8s-ingress-controller/en/latest/deploy/deploy-cic-rancher/) but in the event that it isn't this issue in particular relates to Rancher 2.3.3 and Rancher 2.3.4 RC8 for vSphere built clusters.

I am trying to build a simple standalone ADC deployment of CIC alongside Rancher for bare-metal non-cloud implementation of our in-house software. We've been successful in deploying CIC, NGINX as an ingress and have a good idea of how it should look when finished. However after running through the basic installation of CIC within Rancher we end up with a status of 'Initializing' being displayed.

In all cases the resulting ingress will function correctly and content switches, LB servers will be created successfully. I have tried both using the default namespace and the example separate namespace called 'ingress-citrix' with the same outcome each time.

Reproduce the issue:

1. Build a clean Rancher cluster (1+ nodes) using Flannel networking and default settings
2. Create the ADC user/command policies and authentication secrets accordingly
3. [if required] create a namespace called 'ingress-citrix' and store authentication secret within same ns
4. Download and deploy the edited [CIC deployment file](https://raw.githubusercontent.com/citrix/citrix-k8s-ingress-controller/master/deployment/baremetal/citrix-k8s-cpx-ingress.yml) with added namespace entries within the service account and clusterrolebinding sections in order to place this within 'ingress-citrix' [if required]
5. Download and deploy the unmodified [citrix-rewrite-CRDs](https://github.com/citrix/citrix-k8s-ingress-controller/blob/master/crd/rewrite-responder-policies-deployment.yaml)
6. Create an application deployment, service, ingress e.g.

```
apiVersion: v1
kind: Service
metadata:
  name: hello-world
  namespace: default
  annotations:  
    service.citrix.com/managed-service: "false"
  labels:
    run: hello-world
spec:
  type: NodePort
  ports:
  - port: 80
    protocol: TCP
  selector:
    run: hello-world
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world
  namespace: default
spec:
  selector:
    matchLabels:
      run: hello-world
  replicas: 1
  template:
    metadata:
      labels:
        run: hello-world
    spec:
      containers:
      - name: hello-world
        image: tutum/hello-world
        ports:
        - containerPort: 80
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: hello-world-ingress
  namespace: default
  annotations:
   kubernetes.io/ingress.class: "citrix"
spec:
  rules:
  - host:  www.helloworld.com
    http:
      paths:
      - path: /hello-world
        backend:
          serviceName: hello-world
          servicePort: 80
---
apiVersion: citrix.com/v1
kind: rewritepolicy
metadata:
 name: httpapprootrequestmodify
 namespace: default
spec:
 rewrite-policies:
   - servicenames:
       - hello-world
     rewrite-policy:
       operation: replace
       target: http.req.url
       modify-expression: '"/hello-world/"'
       comment: 'HTTP app root request modify'
       direction: REQUEST
       rewrite-criteria: http.req.url.eq("/hello-world")
```
This will result in a running pod within Rancher displaying a simple hello-world page, an ingress in the state 'Initializing' and all of the expected service groups, vservers, content switch entries etc. in the Citrix ADC.

**NB.** the rewrite policy is not intended to be required in this scenario, but is a more full implementation of how the product is being used in order that it shows the entire configuration.

Viewing the YAML output for the ingress shows:

```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"extensions/v1beta1","kind":"Ingress","metadata":{"annotations":{"kubernetes.io/ingress.class":"citrix"},"name":"hello-world-ingress","namespace":"default"},"spec":{"rules":[{"host":"www.helloworld.com","http":{"paths":[{"backend":{"serviceName":"hello-world","servicePort":80},"path":"/hello-world"}]}}]}}
    kubernetes.io/ingress.class: citrix
  creationTimestamp: "2020-01-13T14:10:00Z"
  generation: 1
  name: hello-world-ingress
  namespace: default
  resourceVersion: "9546632"
  selfLink: /apis/extensions/v1beta1/namespaces/default/ingresses/hello-world-ingress
  uid: 7105a7ba-a8e0-45ed-8f32-7eb37ce1f097
spec:
  rules:
  - host: www.helloworld.com
    http:
      paths:
      - backend:
          serviceName: hello-world
          servicePort: 80
        path: /hello-world
status:
  loadBalancer: {}
```

Please note, I believe that the reason why Rancher does not itself show the ingress status as Active is because it is waiting for an IP address to be entered in the ingress load balancer status field, as per [this description](https://github.com/rancher/rancher/issues/16172#issuecomment-433557721).

I need to understand whether this is due to CIC failing to update the status correctly or Rancher being too stringent around their requirement for an IP address to be shown.

In contrast, when creating an NGINX ingress using the same process the IP address of the node where the ingress is running is updated within the status.

I'm aware of the IPAM and side-car based solutions, perhaps these may even achieve what I'm after but it doesn't make sense why a simple implementation is functional but not seen as such by Rancher.

**Comment by aroraharsh23** [comment]
For consuming ingress, IP address can be provided as annotation. This is an optional field and CIC can consume ingress without IP as well (in specific cases). So, CIC doesn’t mandate that every ingress must have IP address.
So, This is an expected behaviour with CIC deployment.

Also, Your understanding is correct with respect to Rancher behaviour, that it appears too stringent around the requirement for an IP address. So, it remains in “Initializing” state.

**Comment by steviestainz** [comment]
Thank you for your comment, are you referring to `ingress.citrix.com/frontend-ip` in your comment about using an IP address as an annotation? I have defined this annotation within the ingress itself and it results in an empty status entry:

```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-staging
    **ingress.citrix.com/frontend-ip: x.x.x.x**
    ingress.citrix.com/insecure-termination: redirect
    ingress.citrix.com/path-match-method: prefix
    kubernetes.io/ingress.class: citrix
  labels:
    app: aaa
    env: bbb
    release: ccc
  name: dddd
  namespace: eeee
spec:
  rules:
  - host: xxxx
    http:
      paths:
      - backend:
          serviceName: yyyy
          servicePort: http
        path: /path
status:
  loadBalancer: {}
```
If this is the annotation you referred to why isn't it being added to the load balancer IP address of status? Please let me know if the annotation is incorrect or in the wrong place?

**Comment by aroraharsh23** [comment]
Hi, No, "ingress.citrix.com/frontend-ip" will not be applicable here. 
Can we please discuss this on our slack channel. Please refer:
https://github.com/citrix/citrix-k8s-ingress-controller#participate
Let us know, if any issue in issue in participating.

**Comment by verzunof** [comment]
Yes, IP from annotation is not transferred to the status for ingress. Is this required for some functionality?

Thanks

**Comment by pfyod** [comment]
This is a problem for Argo CD too, as it considers Ingress to be healthy if `status.loadBalancer.ingress` is not empty.

**Comment by janrajc** [comment]
@pfyod, @steviestainz  We understood the problem of being not updating the status field of ingress object. We are working on it and will provide the fix soon. I will update here once new CIC with a fix is ready. Thanks for letting us know the issue and its importance.

**Comment by maroshi** [comment]
See more problem reconstruction [report](https://github.com/rancher/rancher/issues/16172#issuecomment-588981030).

**Comment by s012ja** [comment]
Is there any update on this issue?

**Comment by verzunof** [comment]
Ingress status should be filled now with standalone controller and external ADC. 
controller should be started with "--update-ingress-status yes" argument.
sidecar deployment is not yet supported.

**Comment by pfyod** [comment]
> Ingress status should be filled now with standalone controller and external ADC.
> controller should be started with "--update-ingress-status yes" argument.
> sidecar deployment is not yet supported.

Is this already implemented in a published release?

**Comment by kpsmuthu** [comment]
Hi.  Covered here https://github.com/citrix/citrix-k8s-ingress-controller/blob/master/docs/configure/ingress-classes.md#updating-the-ingress-status-for-the-ingress-resources-with-the-specified-ip-address

and release noted here: https://github.com/citrix/citrix-k8s-ingress-controller/releases/tag/1.8.19

**Comment by pfyod** [comment]
@kpsmuthu @verzunof this issue should probably be closed then.

**Comment by steviestainz** [comment]
I'm still able to reproduce this issue when using the following arguments within the CIC deployment yaml:

```
kind: Deployment
metadata:
  name: cic-k8s-ingress-controller
spec:
  selector:
    matchLabels:
      app: cic-k8s-ingress-controller
  replicas: 1
  template:
    metadata:
      name: cic-k8s-ingress-controller
      labels:
        app: cic-k8s-ingress-controller
      annotations:
    spec: 
      serviceAccountName: cic-k8s-role
      containers:
      - name: cic-k8s-ingress-controller
        image: "quay.io/citrix/citrix-k8s-ingress-controller:1.8.19"
        env:
         # Set NetScaler NSIP/SNIP, SNIP in case of HA (mgmt has to be enabled) 
         - name: "NS_IP"
           value: "a.b.c.d"
         - name: "NS_VIP"
           value: "w.x.y.z"
         # Set username for Nitro
         - name: "NS_USER"
           valueFrom:
            secretKeyRef:
             name: nslogin
             key: username
         # Set user password for Nitro
         - name: "NS_PASSWORD"
           valueFrom:
            secretKeyRef:
             name: nslogin
             key: password
         # Set log level
         - name: "LOGLEVEL"
           value: "INFO"
         - name: "EULA"
           value: "yes"
        args:
          - --ingress-classes citrix
          - --feature-node-watch true
          - --update-ingress-status yes
        imagePullPolicy: Always

```
I updated to 1.18.19, deleted the deployment + pod then redeployed, still no difference in behaviour within Rancher. Has anyone else tested this successfully?
