### ISSUE TITLE
IPAM / Ingress Controller keep deleting each others VIPs causing service disruptions

### ISSUE THREAD

**Issue by lhw** [citrix/citrix-k8s-ingress-controller#409]
**Describe the bug**
An address allocated for a loadbalancer will be created and deleted dozens of times a second by the interaction between the ipam and ingress controller

**To Reproduce**
1. Add service with loadbalancer type
2. Wait for provisioning
3. Chaos ensues

**Expected behavior**
- Not spam millions of lines of log and commands.
- Configure IP address.

And I almost consider the last point optional at this point

**Logs**
kubectl logs: https://gist.github.com/lhw/76ef70823251bea2db202d51de951f07

Kubernetes service:
```
intern-nginx-ingress                                 LoadBalancer   10.233.15.65    172.31.203.225   80:31963/TCP,443:31732/TCP     41s
intern-nginx-ingress                                 LoadBalancer   10.233.15.65    <pending>        80:31963/TCP,443:31732/TCP     41s
intern-nginx-ingress                                 LoadBalancer   10.233.15.65    172.31.203.225   80:31963/TCP,443:31732/TCP     41s
intern-nginx-ingress                                 LoadBalancer   10.233.15.65    <pending>        80:31963/TCP,443:31732/TCP     41s
intern-nginx-ingress                                 LoadBalancer   10.233.15.65    172.31.203.225   80:31963/TCP,443:31732/TCP     43s
intern-nginx-ingress                                 LoadBalancer   10.233.15.65    <pending>        80:31963/TCP,443:31732/TCP     43s
intern-nginx-ingress                                 LoadBalancer   10.233.15.65    172.31.203.225   80:31963/TCP,443:31732/TCP     43s
intern-nginx-ingress                                 LoadBalancer   10.233.15.65    <pending>        80:31963/TCP,443:31732/TCP     43s
intern-nginx-ingress                                 LoadBalancer   10.233.15.65    172.31.203.225   80:31963/TCP,443:31732/TCP     44s
intern-nginx-ingress                                 LoadBalancer   10.233.15.65    <pending>        80:31963/TCP,443:31732/TCP     44s
intern-nginx-ingress                                 LoadBalancer   10.233.15.65    172.31.203.225   80:31963/TCP,443:31732/TCP     44s
intern-nginx-ingress                                 LoadBalancer   10.233.15.65    <pending>        80:31963/TCP,443:31732/TCP     44s
intern-nginx-ingress                                 LoadBalancer   10.233.15.65    172.31.203.225   80:31963/TCP,443:31732/TCP     46s
intern-nginx-ingress                                 LoadBalancer   10.233.15.65    <pending>        80:31963/TCP,443:31732/TCP     46s
intern-nginx-ingress                                 LoadBalancer   10.233.15.65    172.31.203.225   80:31963/TCP,443:31732/TCP     46s
intern-nginx-ingress                                 LoadBalancer   10.233.15.65    <pending>        80:31963/TCP,443:31732/TCP     46s
intern-nginx-ingress                                 LoadBalancer   10.233.15.65    172.31.203.225   80:31963/TCP,443:31732/TCP     47s
intern-nginx-ingress                                 LoadBalancer   10.233.15.65    <pending>        80:31963/TCP,443:31732/TCP     47s
intern-nginx-ingress                                 LoadBalancer   10.233.15.65    172.31.203.225   80:31963/TCP,443:31732/TCP     47s
intern-nginx-ingress                                 LoadBalancer   10.233.15.65    <pending>        80:31963/TCP,443:31732/TCP     47s
intern-nginx-ingress                                 LoadBalancer   10.233.15.65    172.31.203.225   80:31963/TCP,443:31732/TCP     49s
intern-nginx-ingress                                 LoadBalancer   10.233.15.65    <pending>        80:31963/TCP,443:31732/TCP     49s
```

**Additional context**

```yaml
# helm values cic chart
adcCredentialSecret: netscaler-login
crds:
  install: true
  retainOnDelete: true
defaultSSLCertSecret: pki-default-certificate
entityPrefix: stg
exporter:
  required: false
image: quay.io/citrix/citrix-k8s-ingress-controller:1.13.15
ingressClass:
- intern
ipam: true
license:
  accept: "yes"
logLevel: info
nodeSelector:
  key: node-role.kubernetes.io/master
  value: ""
nodeWatch: false
nsHTTP2ServerSide: "ON"
nsIP: 172.31.102.23
nsProtocol: https
nsVIP: 172.31.203.22
podIPsforServiceGroupMembers: true
serviceClass:
- intern
tolerations:
- effect: NoSchedule
  key: node-role.kubernetes.io/master
  operator: Equal
updateIngressStatus: true
```
