### ISSUE TITLE
Ratelimit unsupport PATCH http method

### ISSUE THREAD

**Issue by vintury** [citrix/citrix-k8s-ingress-controller#572]
**Describe the bug**
A rate limiting policy cannot be created with a PATCH http method constraint.

**To Reproduce**
1. Steps
```yaml
apiVersion: citrix.com/v1beta1
kind: ratelimit
metadata:
  name: ratelimit-name
spec:
  servicenames:
    - service
  selector_keys:
   basic:
    method:
    - "POST"
    - "PUT"
    - "PATCH"
    - "DELETE"
    per_client_ip: false
  req_threshold: 5
  timeslice: 1000
  throttle_action: "RESPOND"
```
> The ratelimit "ratelimit-name" is invalid: spec.selector_keys.basic.method: Unsupported value: "PATCH": supported values: "GET", "PUT", "POST", "DELETE"

2. Version of the Citrix Ingress Controller
```yaml
image: quay.io/citrix/citrix-k8s-ingress-controller:1.26.7
```
3. Version of MPX/VPX/CPX
```yaml
Platform: NSMPX-5900 8*CPU+8GB+6*E1K+2*IX+1*E1K+1*COL 8925 30130
NetScaler NS13.0: Build 85.19.nc, Date: May 19 2022, 01:11:47   (64-bit)
```
4. Environment variables (minus secrets)
```
KUBERNETES_SERVICE_PORT_HTTPS=443
KUBERNETES_SERVICE_PORT=443
HOSTNAME=cic-citrix-ingress-controller-c9b7799bc-k5qfv
EXPORTER_PORT_8888_TCP_PORT=8888
NS_APPS_NAME_PREFIX=k8s
EULA=true
PWD=/
NS_USER=$$$$$$$$
EXPORTER_PORT=tcp://10.233.13.203:8888
HOME=/root
KUBERNETES_PORT_443_TCP=tcp://10.233.0.1:443
EXPORTER_SERVICE_HOST=10.233.13.203
EXPORTER_SERVICE_PORT=8888
TERM=xterm
SHLVL=1
KUBERNETES_PORT_443_TCP_PROTO=tcp
KUBERNETES_PORT_443_TCP_ADDR=10.233.0.1
NS_IP=$$$$$$
LD_LIBRARY_PATH=/usr/local/lib
EXPORTER_PORT_8888_TCP_ADDR=10.233.13.203
EXPORTER_SERVICE_PORT_EXPORTER_PORT=8888
KUBERNETES_SERVICE_HOST=10.233.0.1
KUBERNETES_PORT=tcp://10.233.0.1:443
KUBERNETES_PORT_443_TCP_PORT=443
EXPORTER_PORT_8888_TCP=tcp://10.233.13.203:8888
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
NS_PASSWORD=$$$$$$$
EXPORTER_PORT_8888_TCP_PROTO=tcp
_=/usr/bin/env
```
**Expected behavior**
Creating ratelimit policy with any available HTTP methods, such as: PATCH, OPTIONS, HEAD, TRACE, etc...

**Logs**
The ratelimit "ratelimit-name" is invalid: spec.selector_keys.basic.method: Unsupported value: "PATCH": supported values: "GET", "PUT", "POST", "DELETE"

**Comment by vintury** [comment]
Any news?

**Comment by arijitray-u** [comment]
PATCH is not supported by NetScaler (ADC).

However, HTTP Methods: HEAD, OPTIONS, TRACE, and CONNECT for authentication, authorization, rate limit, BOT, and WAF policies is now supported . Check release notes for 1.30.1 for details:
[https://github.com/citrix/citrix-k8s-ingress-controller/releases/tag/1.30.1]

**Comment by vintury** [comment]
@arijitray-u you don't right, Citrix ADC support any HTTP Method. 
CIC use "responder policy" for select queries for match **ratelimit** rule.  And "responder policy" support any HTTP method. 
Also, I can specify ANY HTTP method manually. For example, from my ADC:
```python
add responder policy custom_dev_chat_rate_policy "SYS.CHECK_LIMIT(\"custom_dev_chat_rate_policy\") && HTTP.REQ.METHOD.EQ(\"PATCH\") " custom_dev_chat_rate_policy
```

**Comment by arijitray-u** [comment]
@vintury My bad! I should have clarified more.

What I meant was that NetScaler ADC does not support PATCH as an enum in the nitro (REST) call which essentially CIC is using. You can see that in expression editor of NetScaler UI which does not have the patch method listed.

However, I just tested something with the latest CIC and found that we can add PATCH method as enum in CRD and it will be applied on NetScaler. We will officially add this in the CRD soon, but for time being you can do the following as a fix.

1. Add PATCH Enum in CRD (e.g. [ratelimit-crd.yaml](https://github.com/citrix/citrix-k8s-ingress-controller/blob/master/crd/ratelimit/ratelimit-crd.yaml)):
```
 method:
      type: array
      items:
         type: string
         enum: ['GET', 'PUT', 'POST', 'DELETE', 'HEAD', 'OPTIONS', 'TRACE', 'CONNECT','PATCH', 'UNKNOWN_METHOD']
```
2. Apply the modified crd yaml
3. Apply the rate limit policy:
```
apiVersion: citrix.com/v1beta1
kind: ratelimit
metadata:
  name: ratelimit-name
spec:
  servicenames:
    - service
  selector_keys:
   basic:
    method:
    - "POST"
    - "PUT"
    - "PATCH"
    - "DELETE"
    per_client_ip: false
  req_threshold: 5
  timeslice: 1000
  throttle_action: "RESPOND"
```
This should apply policy configuration in NetScaler like below (Please ignore the name as it's specific to my test env) :
`add responder policy tier2_crd_ratelimit_plugin_ratelimit_name "SYS.CHECK_LIMIT(\"tier2_crd_ratelimit_plugin_ratelimit_name\") && (HTTP.REQ.METHOD.EQ(\"POST\") || HTTP.REQ.METHOD.EQ(\"PUT\") || HTTP.REQ.METHOD.EQ(\"PATCH\") || HTTP.REQ.METHOD.EQ(\"DELETE\"))" tier2_crd_ratelimit_plugin_ratelimit_name`
