### ISSUE TITLE
Wildcards

### ISSUE THREAD

**Issue by alatdev** [citrix/citrix-k8s-ingress-controller#7]
Hi,

as far as i found out, the path variable from the ingress.yaml is converted in the form of HTTP.REQ.URL.PATH.EQ("path") to a CS-Policy.

But how can i use wildcards?

```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: nginx-ingress
  annotations:
   NETSCALER_HTTP_PORT: "80"
   NETSCALER_VIP: "192.168.44.87"
   kubernetes.io/ingress.class: "citrix"
spec:
  rules:
  - http:
      paths:
      - path: /nginx-test
        backend:
          serviceName: my-nginx
          servicePort: 8080
```
